In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as st

homeless_2017_csv = "datasets/2017-Point-in-Time-Estimates-by-state.csv"
homeless_2020_csv = "datasets/2020-Point-in-Time-Estimates-by-state.csv"

states_homeless_2017_data_df = pd.read_csv(homeless_2017_csv).set_index('State')
states_homeless_2020_data_df = pd.read_csv(homeless_2020_csv).set_index('State')

states_homeless_2017_data_df.head()

,Number of CoCs,"Overall Homeless, 2017","Overall Homeless - Under 18, 2017","Overall Homeless - Age 18 to 24, 2017","Overall Homeless - Over 24, 2017","Overall Homeless - Female, 2017","Overall Homeless - Male, 2017","Overall Homeless - Transgender, 2017","Overall Homeless - Gender Non-Conforming, 2017","Overall Homeless - Non-Hispanic/Non-Latino, 2017",...,"Overall Homeless Parenting Youth Age 18-24, 2017","Sheltered ES Homeless Parenting Youth Age 18-24, 2017","Sheltered TH Homeless Parenting Youth Age 18-24, 2017","Sheltered Total Homeless Parenting Youth Age 18-24, 2017","Unsheltered Homeless Parenting Youth Age 18-24, 2017","Overall Homeless Children of Parenting Youth, 2017","Sheltered ES Homeless Children of Parenting Youth, 2017","Sheltered TH Homeless Children of Parenting Youth, 2017","Sheltered Total Homeless Children of Parenting Youth, 2017","Unsheltered Homeless Children of Parenting Youth, 2017"
State,,,,,,,,,,,,,,,,,,,,,
AK,2.0,"1,845",305,186,"1,354",765,"1,075",4,1.0,"1,743",...,22,10,12,22,0.0,39,20,19,39,0.0
AL,8.0,"3,793",528,300,"2,965","1,314","2,453",21,5.0,"3,721",...,23,6,14,20,3.0,39,11,24,35,4.0
AR,6.0,"2,467",265,209,"1,993",965,"1,499",3,0.0,"2,405",...,10,8,2,10,0.0,13,11,2,13,0.0
AZ,3.0,"8,947","1,607",660,"6,680","3,331","5,592",22,2.0,"6,876",...,81,37,44,81,0.0,112,55,57,112,0.0
CA,43.0,"131,532","14,207","13,276","104,049","42,750","87,609",793,380.0,"90,040",...,770,248,397,645,125.0,912,289,493,782,130.0

In [19]:
total_nonhispanic_nonlatino = states_homeless_2017_data_df.loc['Total','Overall Homeless - Non-Hispanic/Non-Latino, 2017']
converted_total_nonhispanic_nonlatino = total_nonhispanic_nonlatino.replace(',', '')
converted_total_nonhispanic_nonlatino = int(converted_total_nonhispanic_nonlatino)
print(converted_total_nonhispanic_nonlatino)

432634

In [20]:
total_hispanic_latino = states_homeless_2017_data_df.loc['Total','Overall Homeless - Hispanic/Latino, 2017']
converted_total_hispanic_latino = total_hispanic_latino.replace(',', '')
converted_total_hispanic_latino = int(converted_total_hispanic_latino)
print(converted_total_hispanic_latino)

118362

In [21]:
total_white = states_homeless_2017_data_df.loc['Total','Overall Homeless - White, 2017']
converted_total_white = total_white.replace(',', '')
converted_total_white = int(converted_total_white)
print(converted_total_white)

259675

In [22]:
total_black__or_african_american = states_homeless_2017_data_df.loc['Total','Overall Homeless - Black or African American, 2017']
converted_total_black__or_african_american = total_black__or_african_american.replace(',', '')
converted_total_black__or_african_american = int(converted_total_black__or_african_american)
print(converted_total_black__or_african_american)

223690

In [23]:
total_asian = states_homeless_2017_data_df.loc['Total','Overall Homeless - Asian, 2017']
converted_total_asian = total_asian.replace(',', '')
converted_total_asian = int(converted_total_asian)
print(converted_total_asian)

6700

In [24]:
total_american_indian_or_alaskan_native = states_homeless_2017_data_df.loc['Total','Overall Homeless - American Indian or Alaska Native, 2017']
converted_total_american_indian_or_alaskan_native = total_american_indian_or_alaskan_native.replace(',', '')
converted_total_american_indian_or_alaskan_native = int(converted_total_american_indian_or_alaskan_native)
print(converted_total_american_indian_or_alaskan_native)

16741

In [25]:
total_native_hawaiian_or_other_pacific_islander = states_homeless_2017_data_df.loc['Total','Overall Homeless - Native Hawaiian or Other Pacific Islander, 2017']
converted_total_native_hawaiian_or_other_pacific_islander = total_native_hawaiian_or_other_pacific_islander.replace(',', '')
converted_total_native_hawaiian_or_other_pacific_islander = int(converted_total_native_hawaiian_or_other_pacific_islander)
print(converted_total_native_hawaiian_or_other_pacific_islander)

8515

In [26]:
total_multiple_races = states_homeless_2017_data_df.loc['Total','Overall Homeless - Multiple Races, 2017']
converted_total_multiple_races = total_multiple_races.replace(',', '')
converted_total_multiple_races = int(converted_total_multiple_races)
print(converted_total_multiple_races)

35675